### ISSUE TITLE
Same Hashes for Multiple File

### ISSUE THREAD

**Issue by realph** [Luismahou/grunt-hashres#57]
When hashres is run, it sets unique hashes on all the files. Is it possible to have the same hash used on multiple files when I run hashres? Like so:

    app.js?v=123
    app.css?v=123 
    vendor.css?v=123

Thanks!

**Comment by Luismahou** [comment]
Nope. The hash depends on the file contents, otherwise I cannot ensure cache would be invalidated properly.
